spring:
  application:
    name: access-guard

  redis:
    host: ${SPRING_DATA_REDIS_HOST:redis}
    port: ${SPRING_DATA_REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://localhost:5432/friend_db?currentSchema=auth_schema
    username: friend
    password: friend
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS auth_schema
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    root: INFO

app:
  jwt:
    tokenExpiration: ${APP_JWT_TOKEN_EXPIRATION:30m}
    refreshTokenExpiration: ${APP_JWT_REFRESH_TOKEN_EXPIRATION:30d}