version: '3.0'

services:
  redis:
    image: redis:7-alpine
    container_name: accessguard-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: accessguard-postgres
    environment:
      POSTGRES_DB: accessguard_db
      POSTGRES_USER: accessguard_user
      POSTGRES_PASSWORD: accessguard_pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped




# cd docker
# docker-compose up


#Команда Docker-Compose up развёртывает сервисы веб-приложений и создаёт из docker-образа новые контейнеры, а также сети, тома и все конфигурации, указанные в файле Docker Compose.
# Добавляя флаг -d, вы выполняете команду в раздельном или фоновом режиме, сохраняя возможность управления терминалом (чуть ниже рассмотрим примеры для наглядности).